server:
  port: 9900
  name: springboot2

# change
project-config:
  mysql:
    url: 150.109.49.131:3306
    username: Ja0VJiQhQdGf/uZ0rqO/ftbMFcdQUOxH+27uuv7KGhmxWuLb0mlTD87k8X929SuQKji97a960q3qMJddq5Etvw==
    password: mWt90GLbtqxthZer/enAAPloHGTmUCHDfe74w5xTv9GjXga8dO2mSnmSZoMqwi3Uxuo14NLkNP9Ko8ZSyvogRw==
    publicKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKNPt2hXD5FXkLFdNKTlDraPvDxcs54CP/aIF4POS2P0OzI03nEMdjy+NNBzrIGVEJykoaKdxE8q0oheovEg/RUCAwEAAQ==

spring:
  application:
    name: springboot2
  mail:
    host: smtp.163.com
    username: maduar@163.com
    password: 163maduar310
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      test:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://${project-config.mysql.url}/test?useUnicode=true&characterEncoding=utf8
        username: ${project-config.mysql.username}
        password: ${project-config.mysql.password}
        connectionProperties: "config.decrypt=true;config.decrypt.key=${project-config.mysql.publickey}"
        validation-query: select 1
        validation-interval: 30000
        initial-size: 3
        max-active: 100
        min-idle: 10
        time-between-eviction-runs-millis: 30000
        suspect-timeout: 60
        log-abandoned: false
        abandon-when-percentage-full: 50
        min-evictable-idle-time-millis: 60000
        testOnBorrow: true
        testWhileIdle: true
        filters: stat,config
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
#      connectionProperties:
#        config:
#          decrypt: true
#            key: ${public-key}
#        druid:
#          stat:
#            mergeSql: true
#            slowSqlMillis: 5000
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true
#      aop-patterns: com.ebizprise.das.web.service.*.*

mybatis:
  mapUnderscoreToCamelCase: true
  typeAliasesPackage: com.maduar.springboot2.mybatis.model
